version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mybackend-db
    environment:
      MYSQL_ROOT_PASSWORD: Root@1234
      MYSQL_DATABASE: dev
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my_shared_network

volumes:
  mysql-data:

networks:
  my_shared_network:
    external: true
